version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt -t package/

  build:
    commands:
      - cp lambda_function.py package/
      - cd package
      - zip -r ../lambda_function.zip .

  post_build:
    commands:
      - aws lambda update-function-code --function-name JSON-File-Processing --zip-file fileb://lambda_function.zip
      - echo "Lambda function successfully updated!"
