version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt -t .

  build:
    commands:
      - zip -r lambda_function.zip .

  post_build:
    commands:
      - aws lambda update-function-code --function-name JSON-File-Processing --zip-file fileb://lambda_function.zip --region us-east-1
      - echo "Lambda function successfully updated!"
